apiVersion: v1
kind: Service
metadata:
  name: ds-service
  namespace: churninsight
spec:
  selector:
    app: ds-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
